config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/about'
  get 'pages/contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container mx-auto justify-center h-16 flex w-1/2 mt-8 px-8 font-bold text-blue-600">
  <p>Todos os direitos reservado</p>
</div>

app/views/layouts/_navbar.html.erb
<div class="container mx-auto justify-center h-16 flex w-1/2 mb-2 px-8">
  <div class="grid grid-cols-2 grid-flow-row w-full content-center">
    <div><%= image_tag 'logo.png' %></div>
    <div class="flex justify-end items-center space-x-2">
      <%=link_to 'Home |', root_path%>
      <%=link_to 'Quem somos |', pages_about_path%>
      <%=link_to 'Contato', pages_contact_path%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UNES</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <main>
      <%= yield %>
    </main>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mx-auto justify-center flex w-1/2 mb-2 px-6">
  <div class="grid grid-cols-1 grid-flow-row">
    <div>
      <h1 class="text-2xl font-bold">Quem somos</h1>
    </div>
      <p class="text-justify mt-2">
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
      </p>
      <p class="text-justify mt-4 text-2xl font-bold">
        5 motivos para estudar
      </p>
    <ol class="list-decimal px-6 mt-4 list-outside">
      <li>Material sempre atualizado</li>
      <li>Tablest em sala de aula</li>
      <li>Professores renomado</li>
      <li>Universidade bem avaliada</li>
      <li>Ótima localização</li>
    </ol>

    <div class="border-b-4 justify-center mt-4"></div>

    <div>
      <h1 class="text-2xl font-bold mt-4">Objetivos</h1>
    </div>
    <p class="text-justify mt-2">
      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
    </p>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container mx-auto justify-center flex w-1/2 mb-2 px-6">
  <div class="grid grid-cols-1 grid-flow-row">
    <div>
      <h1 class="text-2xl font-bold">Entre em contato</h1>
    </div>
    <p class="text-justify mt-2">
      It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
    </p>

    <div class="border-b-4 justify-center mt-4 mb-4"></div>

    <form class="w-1/2">

      <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Seu e-mail:</label>
      <input type="email" id="email" aria-describedby="helper-text-explanation" class="bg-gray-50 border border-gray-300
      text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">

      <label for="email" class="block mb-2 text-sm font-medium text-gray-900">Assunto:</label>
      <input type="email" id="email" aria-describedby="helper-text-explanation" class="bg-gray-50 border border-gray-300
      text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">

      <label for="message" class="block mb-2 text-sm font-medium text-gray-900">Descrição:</label>
      <textarea id="message" rows="4" class="block p-2.5 w-full text-sm text-gray-900 rounded-lg border
      border-gray-300 focus:ring-blue-500 focus:border-blue-500"></textarea>

      <button type="submit" class="mt-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none
      focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600
      dark:hover:bg-blue-700 dark:focus:ring-blue-800">Enviar</button>
    </form>

  </div>
</div>

app/views/pages/home.html.erb
<div class="container mx-auto justify-center flex w-1/2 mb-2 px-6">
  <div class="grid grid-cols-1 grid-flow-row">
  <div>
    <%= image_tag 'capa.png' %>
  </div>
  <div class="mt-2">
    <h1 class="text-2xl font-bold">Sobre a universidade</h1>
    <p class="text-justify mt-2">
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>
    <p class="text-justify mt-4">
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
    </p>
  </div>
  </div>
</div>